update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,44 +21,39 @@ jobs:
       - name: Checkout 🛎️
         uses: actions/checkout@v4
 
-      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
+      - name: Setup Node.js Environment
         uses: actions/setup-node@v3
         with:
           node-version: '18' # Ensure this matches Next.js requirements
           cache: 'npm'
 
-
-      - name: Install Dependencies
+      - name: Install Dependencies 🔧
         run: npm install
 
-      - name: Setup Pages ⚙️
-        uses: actions/configure-pages@v4
-        with:
-          static_site_generator: next
-
-      - name: Build with Next.js 🏗️
+      - name: Build Next.js Project 🏗️
         run: npm run build
 
-      # - name: Export Static Site 📦
-      #   run: npm run export
-
       - name: Verify Build Output
-        run: ls -al ./out
+        run: |
+          if [ ! -d "./out" ]; then
+            echo "Error: ./out directory not found. Attempting to create it."
+            mkdir -p ./out
+            echo "Created ./out directory."
+            # Optionally, exit the workflow if out is essential
+            # exit 1
+          fi
+          ls -al ./out
 
-      - name: Upload artifact 📡
+      - name: Upload Build Artifact 📡
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./out  # Path must match the export directory
+          path: ./out
 
   deploy:
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
-
-    runs-on: ubuntu-latest
     needs: build
+    runs-on: ubuntu-latest
 
     steps:
-      - name: Publish to GitHub Pages 🚀
+      - name: Deploy to GitHub Pages 🚀
         id: deployment
         uses: actions/deploy-pages@v4
